name = "airtheon"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "airtheon-prod"
database_id = "14f845d1-8b6a-4677-a9f3-a95bfc23e772"
migrations_dir = "./src/db/migrations"

[[r2_buckets]]
binding = "R2"
bucket_name = "airtheon-assets"

[vars]
NEXT_PUBLIC_BASE_DOMAIN="airtheon.com"
NEXT_PUBLIC_HELP_DOMAIN="help.airtheon.com"
NEXT_PUBLIC_BASE_URL="https://airtheon.com"
NEXT_PUBLIC_HELP_URL="https://help.airtheon.com"
BETTER_AUTH_URL="https://airtheon.com"
